# Generated by Django 5.1.3 on 2024-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('passenger_capacity', models.IntegerField()),
                ('car_model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('under maintenance', 'Under Maintenance')], max_length=20)),
            ],
        ),
    ]
