# Generated by Django 5.1.3 on 2024-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('appetizer', 'Appetizer'), ('main course', 'Main Course'), ('dessert', 'Dessert')], max_length=20)),
                ('cuisine', models.CharField(max_length=100)),
            ],
        ),
    ]
